name: Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      # 레포지토리에 체크아웃하여 소스를 가져온다.
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 노드 설치
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      # pnpm global install
      - name: install pnpm
        run: npm i pnpm@latest -g

      # 의존성 설치한다.
      - name: Install dependencies
        run: pnpm install

      # 빌드
      - name: Build App
        run: pnpm build
