name: Changesets

on:
  push:
    paths:
      - '.changeset/**'
    branches:
      - main
job:
  release:
    name: Release
    runs-on: ubuntu-latest
    step:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          
      - name: pnpm Install
        run: npm i pnpm@latest -g
        
      - name: dependencies Install
        run: pnpm install
        
      - name: Create release Pull Request or Publish to Github Packages
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
